### ISSUE TITLE
Mystical Agriculture Inferium Crops Recipe in Botania

### ISSUE THREAD

**Issue by kulflame** [Drakma/VacantSky#4] opened 2016-11-10 10:46 UTC
It seems that sometimes the recipe uses the mana in the mana pool and sometimes it doesn't. 

I made 9 Inferior Inferium Crops and it didn't use any mana (just required half a pool).
I made 3 Prudent Inferium Crops and it didn't use any mana (just required half a pool).
I made 1 Intermediate Inferium Crop and it DID use half of my mana pool.
I made 3 Supreme Inferium Crops and it didn't use any mana (just required half a pool).

**Comment by Drakma** [comment] 2016-11-11 00:52
I've posted an issue @ https://github.com/Vazkii/Botania/issues/1958

we'll see his response

**Comment by kulflame** [comment] 2016-12-06 23:34
Just an update for ya; it takes a set amount of mana now and seems to be about 1/8 - 1/10 of a mana pool per but the JEI shows it requires a half-full mana pool.

**Comment by Drakma** [comment] 2016-12-07 08:45
I've updated modtweaker and some of the recipes.  I should have an update out tomrrow.
On Dec 6, 2016, at 5:34 PM, Kulflame <notifications@github.com<mailto:notifications@github.com>> wrote:

Just an update for ya; it takes a set amount of mana now and seems to be about 1/8 - 1/10 of a mana pool per but the JEI shows it requires a half-full mana pool.

**Comment by Drakma** [comment] 2016-12-07 20:54
There appears to be a known JEI error where the incorrect data is being displayed.  I'll close this for now but keep an eye on it as the recipes are actually working as intended and it's just presentation

**Closed as completed by Drakma** 2016-12-07 20:54 UTC
